image: Ubuntu

stack: jdk 11, docker

branches:
  only:
    - main

build: off

environment:
  matrix:
    - job_name: msql
    - job_name: psql

for:
  -
    matrix:
      only:
        - job_name: msql

    install:
      - docker compose down &
      - sleep 10s
      - docker compose up &
      - sleep 1m
      - java -jar artifacts/aqa-shop.jar --spring.profiles.active=msql &
      - sleep 20s

    build_script:
      - chmod +x gradlew
      - ./gradlew clean test -Ddb.url=jdbc:mysql://localhost:3306/msql -Dschemas=msql -Dselenide.headless=true

  -
    matrix:
      only:
        - job_name: psql
        - job_depends_on: msql

    install:
      - docker compose down &
      - sleep 10s
      - docker compose up &
      - sleep 1m
      - java -jar artifacts/aqa-shop.jar --spring.profiles.active=psql &
      - sleep 20s

    build_script:
      - chmod +x gradlew
      - ./gradlew clean test -Ddb.url=jdbc:postgresql://localhost:5432/psql -Dschemas=public -Dselenide.headless=true