version: '3.7'
services:
  mysql:
    image: mysql:8.0
    restart: always
    ports:
      - '3306:3306'
    volumes:
      - ./data_mysql:/var/lib/mysql
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=msql
      - MYSQL_USER=app
      - MYSQL_PASSWORD=pass
  postgres:
    image: postgres:12.11-alpine
    ports:
      - '5432:5432'
    volumes:
      - ./data_postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: psql
      POSTGRES_USER: app
      POSTGRES_PASSWORD: pass
  node-app:
    build: ./gate-simulator
    image: node-app:1.0
    ports:
      - '9999:9999'